title: Clase de Machine Learning 2
logo: /images/escudo.jpg
description: Clase de Machine Learning 2 en la Universidad Panamericana
google_analytics: 
show_downloads: true
theme: jekyll-theme-primer

gems:
  - jekyll-mentions
