title: Clase de Deep Learning
logo: /images/escudo.jpg
description: Clase de Deep Learning de la Universidad Panamericana
google_analytics: 
show_downloads: true
theme: jekyll-theme-primer

gems:
  - jekyll-mentions
